"""
research_engine/writer/reference_manager.py
Tier 3 — Reference manager integration (Zotero/Mendeley)

Import and export references in BibTeX and RIS formats, enabling
round-tripping between the Research Analysis Toolkit and external
reference managers.

BibTeX  — Zotero, Mendeley, JabRef, Overleaf
RIS     — EndNote, Mendeley, Zotero, ProQuest

Public API
----------
    export_bibtex(ref_list, output_path)            → Path
    export_ris(ref_list, output_path)               → Path
    import_bibtex(input_path)                       → list[ReferenceEntry]
    import_ris(input_path)                         → list[ReferenceEntry]
    export_to_zotero(ref_list, output_path)         → Path (.bib)
    export_to_mendeley(ref_list, output_path)       → Path (.ris)
"""
from __future__ import annotations

import re
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ══════════════════════════════════════════════════════════════
# BibTeX Export
# ══════════════════════════════════════════════════════════════

def _make_bibtex_key(author: str, year: str, title: str = "") -> str:
    """Generate a BibTeX citation key: surname + year + first word of title."""
    surname = author.split(",")[0].split("&")[0].split("and")[0].strip().lower()
    surname = re.sub(r'[^a-z]', '', surname)
    first_word = re.sub(r'[^a-z]', '', (title or "").split()[0].lower()) if title else ""
    return f"{surname}{year}{first_word}"


def export_bibtex(ref_list, output_path: str | Path) -> Path:
    """
    Export a ReferenceList to a .bib file (BibTeX format).

    Each entry is converted to a BibTeX @article or @book entry.
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = ["% Generated by Research Analysis Toolkit",
             "% APA 7th edition compliant references",
             ""]

    for entry in ref_list.entries:
        key = _make_bibtex_key(entry.author, entry.year, entry.full_text[:50])
        source_type = getattr(entry, "source_type", "journal") or "journal"
        bib_type = "article" if source_type == "journal" else "book" if source_type == "book" else "incollection" if source_type == "chapter" else "misc"

        # Parse the full text for fields
        fields = _parse_ref_fields(entry.full_text)

        lines.append(f"@{bib_type}{{{key},")
        lines.append(f"  author    = {{{entry.author}}},")
        lines.append(f"  year      = {{{entry.year}}},")

        if fields.get("title"):
            lines.append(f"  title     = {{{{{fields['title']}}}}},")  # double braces for title preservation
        if fields.get("journal"):
            lines.append(f"  journal   = {{{fields['journal']}}},")
        if fields.get("volume"):
            lines.append(f"  volume    = {{{fields['volume']}}},")
        if fields.get("issue"):
            lines.append(f"  number    = {{{fields['issue']}}},")
        if fields.get("pages"):
            lines.append(f"  pages     = {{{fields['pages']}}},")
        if fields.get("doi"):
            lines.append(f"  doi       = {{{fields['doi']}}},")
        if fields.get("publisher"):
            lines.append(f"  publisher = {{{fields['publisher']}}},")
        if fields.get("url"):
            lines.append(f"  url       = {{{fields['url']}}},")

        # Remove trailing comma from last field
        if lines[-1].endswith(","):
            lines[-1] = lines[-1][:-1]

        lines.append("}")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    return out


# ══════════════════════════════════════════════════════════════
# RIS Export
# ══════════════════════════════════════════════════════════════

def export_ris(ref_list, output_path: str | Path) -> Path:
    """
    Export a ReferenceList to a .ris file (RIS format).
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = []

    for entry in ref_list.entries:
        source_type = getattr(entry, "source_type", "journal") or "journal"
        ris_type = "JOUR" if source_type == "journal" else "BOOK" if source_type == "book" else "CHAP" if source_type == "chapter" else "ELEC" if source_type == "website" else "THES"

        lines.append(f"TY  - {ris_type}")
        lines.append(f"AU  - {entry.author}")
        lines.append(f"PY  - {entry.year}")

        fields = _parse_ref_fields(entry.full_text)
        if fields.get("title"):
            lines.append(f"TI  - {fields['title']}")
        if fields.get("journal"):
            lines.append(f"JO  - {fields['journal']}")
        if fields.get("volume"):
            lines.append(f"VL  - {fields['volume']}")
        if fields.get("issue"):
            lines.append(f"IS  - {fields['issue']}")
        if fields.get("pages"):
            lines.append(f"SP  - {fields['pages']}")
        if fields.get("doi"):
            lines.append(f"DO  - {fields['doi']}")
        if fields.get("publisher"):
            lines.append(f"PB  - {fields['publisher']}")
        if fields.get("url"):
            lines.append(f"UR  - {fields['url']}")

        lines.append("ER  -")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    return out


# ══════════════════════════════════════════════════════════════
# BibTeX Import
# ══════════════════════════════════════════════════════════════

def import_bibtex(input_path: str | Path) -> list:
    """
    Import references from a .bib file.

    Returns a list of ReferenceEntry objects.
    """
    from research_engine.writer.reference_generator import ReferenceEntry

    text = Path(input_path).read_text(encoding="utf-8", errors="replace")
    entries = []

    # Parse BibTeX entries
    pattern = re.compile(
        r'@(\w+)\{([^,]+),\s*(.*?)\n\}',
        re.DOTALL
    )

    for m in pattern.finditer(text):
        bib_type = m.group(1).lower()
        cite_key = m.group(2).strip()
        fields_text = m.group(3)

        fields = _parse_bibtex_fields(fields_text)

        author = fields.get("author", cite_key)
        year = fields.get("year", "")

        # Build full text in APA 7th style
        from research_engine.writer.apa_formatter import build_apa_reference
        full_text = build_apa_reference(
            author=author,
            year=year,
            title=fields.get("title", ""),
            journal=fields.get("journal", ""),
            volume=fields.get("volume", ""),
            issue=fields.get("number", ""),
            pages=fields.get("pages", ""),
            doi=fields.get("doi", ""),
            publisher=fields.get("publisher", ""),
            url=fields.get("url", ""),
            source_type="journal" if bib_type == "article" else
                       "book" if bib_type == "book" else
                       "chapter" if bib_type == "incollection" else
                       "website" if bib_type == "misc" else "journal"
        )

        entry = ReferenceEntry(
            key=cite_key,
            author=author,
            year=year,
            full_text=full_text,
            source_type="journal" if bib_type == "article" else
                       "book" if bib_type == "book" else
                       "chapter" if bib_type == "incollection" else "journal"
        )
        entries.append(entry)

    return entries


def _parse_bibtex_fields(text: str) -> dict[str, str]:
    """Parse BibTeX field assignments into a dict."""
    fields = {}
    pattern = re.compile(r'(\w+)\s*=\s*\{(.+?)\}', re.DOTALL)
    for m in pattern.finditer(text):
        key = m.group(1).strip().lower()
        val = m.group(2).strip()
        # Remove nested braces from title
        if key == "title":
            val = val.replace("{", "").replace("}", "")
        fields[key] = val
    return fields


# ══════════════════════════════════════════════════════════════
# RIS Import
# ══════════════════════════════════════════════════════════════

def import_ris(input_path: str | Path) -> list:
    """
    Import references from a .ris file.

    Returns a list of ReferenceEntry objects.
    """
    from research_engine.writer.reference_generator import ReferenceEntry
    from research_engine.writer.apa_formatter import build_apa_reference

    text = Path(input_path).read_text(encoding="utf-8", errors="replace")
    entries = []

    # Split on ER
    records = text.split("ER  -")
    for record in records:
        if not record.strip():
            continue

        fields = {}
        for line in record.strip().split("\n"):
            line = line.strip()
            if len(line) >= 6:
                tag = line[:2]
                val = line[6:].strip() if len(line) > 6 else ""
                tag_map = {"AU": "author", "PY": "year", "TI": "title",
                           "JO": "journal", "VL": "volume", "IS": "issue",
                           "SP": "pages", "DO": "doi", "PB": "publisher",
                           "UR": "url", "TY": "type"}
                if tag in tag_map:
                    fields[tag_map[tag]] = val

        if not fields.get("author") or not fields.get("year"):
            continue

        source_type = "journal"
        if fields.get("type") == "BOOK":
            source_type = "book"
        elif fields.get("type") == "CHAP":
            source_type = "chapter"
        elif fields.get("type") == "ELEC":
            source_type = "website"
        elif fields.get("type") == "THES":
            source_type = "thesis"

        full_text = build_apa_reference(
            author=fields.get("author", ""),
            year=fields.get("year", ""),
            title=fields.get("title", ""),
            journal=fields.get("journal", ""),
            volume=fields.get("volume", ""),
            issue=fields.get("issue", ""),
            pages=fields.get("pages", ""),
            doi=fields.get("doi", ""),
            publisher=fields.get("publisher", ""),
            url=fields.get("url", ""),
            source_type=source_type
        )

        key = f"{fields.get('author', 'unknown').split(',')[0].strip().lower()}_{fields.get('year', '')}"
        entry = ReferenceEntry(
            key=key, author=fields.get("author", ""),
            year=fields.get("year", ""),
            full_text=full_text, source_type=source_type
        )
        entries.append(entry)

    return entries


# ══════════════════════════════════════════════════════════════
# Convenience wrappers
# ══════════════════════════════════════════════════════════════

def export_to_zotero(ref_list, output_path: str | Path) -> Path:
    """Export references for import into Zotero (.bib format)."""
    return export_bibtex(ref_list, output_path)


def export_to_mendeley(ref_list, output_path: str | Path) -> Path:
    """Export references for import into Mendeley (.ris format)."""
    return export_ris(ref_list, output_path)


# ══════════════════════════════════════════════════════════════
# Helper: parse reference text fields
# ══════════════════════════════════════════════════════════════

def _parse_ref_fields(text: str) -> dict[str, str]:
    """Extract structured fields from a reference text string."""
    fields = {}
    if not text:
        return fields

    # Extract DOI
    doi_match = re.search(r'(?:https?://)?(?:dx\.)?doi\.org/(.+?)(?:\s|$)', text, re.IGNORECASE)
    if doi_match:
        fields["doi"] = doi_match.group(1).rstrip(".")

    # Extract pages (xx-xx or xx-x format)
    pages_match = re.search(r',\s*(\d+[-–]\d+)\s*', text)
    if pages_match:
        fields["pages"] = pages_match.group(1)

    # Extract volume(issue)
    vi_match = re.search(r',?\s*(\d+)\((\d+)\)', text)
    if vi_match:
        fields["volume"] = vi_match.group(1)
        fields["issue"] = vi_match.group(2)
    else:
        vol_match = re.search(r',\s*(\d+),\s', text)
        if vol_match:
            fields["volume"] = vol_match.group(1)

    # Extract URL
    url_match = re.search(r'(https?://\S+)', text)
    if url_match:
        fields["url"] = url_match.group(1).rstrip(".")

    return fields
