"""
research_engine/writer/spss_sync.py
Tier 2 — SPSS ↔ Chapter 3 methodology synchronisation

Ensures the variable labels and value labels in the generated .sps file
exactly match how Chapter 3 describes the measurement instrument.

Also generates a "Methods" text block that can be inserted into
Chapter 3 describing each variable, its scale, and coding scheme —
derived directly from the questionnaire config and SPSS labels.

Public API
----------
    extract_spss_variables(sps_path)                     → list[SPSSVariable]
    generate_methods_paragraph(session, study_dir)       → str
    check_consistency(sps_path, questionnaire_path)      → ConsistencyReport
    write_methods_section(session, study_dir, api_key)   → str
"""
from __future__ import annotations

import re
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class SPSSVariable:
    name:         str
    label:        str
    value_labels: dict[str, str] = field(default_factory=dict)  # "1" → "Strongly Disagree"
    var_type:     str = "numeric"

    def to_methods_line(self) -> str:
        vals = ", ".join(f"{k}={v}" for k, v in self.value_labels.items())
        return f"  {self.name} ({self.label}): {vals if vals else 'continuous'}"


@dataclass
class ConsistencyReport:
    matches:      list[str] = field(default_factory=list)
    mismatches:   list[str] = field(default_factory=list)
    missing_sps:  list[str] = field(default_factory=list)   # in questionnaire but not .sps
    missing_q:    list[str] = field(default_factory=list)   # in .sps but not questionnaire

    @property
    def is_consistent(self) -> bool:
        return len(self.mismatches) == 0 and len(self.missing_sps) == 0

    def summary(self) -> str:
        lines = [
            f"Matches:   {len(self.matches)}",
            f"Mismatches: {len(self.mismatches)}",
            f"Missing from SPS: {len(self.missing_sps)}",
            f"Missing from questionnaire: {len(self.missing_q)}",
        ]
        if self.mismatches:
            lines.append("\nMismatches:")
            for m in self.mismatches[:10]:
                lines.append(f"  ⚠  {m}")
        return "\n".join(lines)


# ══════════════════════════════════════════════════════════════
# SPS file parser
# ══════════════════════════════════════════════════════════════

def extract_spss_variables(sps_path: str | Path) -> list[SPSSVariable]:
    """
    Parse a .sps syntax file and extract variable names, labels, and value labels.

    Handles the VARIABLE LABELS and VALUE LABELS blocks generated by
    research_engine/exporters/spss_exporter.py.
    """
    text = Path(sps_path).read_text(encoding="utf-8", errors="replace")
    variables: dict[str, SPSSVariable] = {}

    # ── VARIABLE LABELS block ─────────────────────────────────
    vl_block = re.search(
        r'VARIABLE\s+LABELS\s*(.*?)\s*\.\s*(?=\n[A-Z]|\Z)',
        text, re.DOTALL | re.IGNORECASE
    )
    if vl_block:
        for m in re.finditer(r'(\w+)\s+["\']([^"\']+)["\']', vl_block.group(1)):
            name, label = m.group(1), m.group(2)
            variables[name] = SPSSVariable(name=name, label=label)

    # ── VALUE LABELS block ────────────────────────────────────
    val_block = re.search(
        r'VALUE\s+LABELS\s*(.*?)\s*\.\s*(?=\n[A-Z]|\Z)',
        text, re.DOTALL | re.IGNORECASE
    )
    if val_block:
        # Each /var_name "1" "label" "2" "label" ...
        for chunk in re.split(r'\n\s*/', val_block.group(1)):
            chunk = chunk.strip()
            if not chunk:
                continue
            name_m = re.match(r'(\w+(?:\s+\w+)*)\s+', chunk)
            if not name_m:
                continue
            var_names = name_m.group(1).split()
            val_pairs = re.findall(r'(\d+(?:\.\d+)?)\s+["\']([^"\']+)["\']', chunk)
            for vname in var_names:
                if vname not in variables:
                    variables[vname] = SPSSVariable(name=vname, label=vname)
                for code, label in val_pairs:
                    variables[vname].value_labels[code] = label

    return list(variables.values())


# ══════════════════════════════════════════════════════════════
# Consistency checker
# ══════════════════════════════════════════════════════════════

def check_consistency(
    sps_path:           str | Path,
    questionnaire_path: str | Path,
) -> ConsistencyReport:
    """
    Compare variable labels between the .sps file and questionnaire.json.

    Returns a ConsistencyReport flagging mismatches.
    """
    report = ConsistencyReport()

    sps_vars = {v.name: v for v in extract_spss_variables(sps_path)}

    with open(questionnaire_path, encoding="utf-8") as f:
        q_data = json.load(f)

    q_items: dict[str, str] = {}  # var_name → item_text
    scale = q_data.get("scale", {})

    for sec_key, sec in q_data.get("sections", {}).items():
        for i, item_text in enumerate(sec.get("items", []), start=1):
            var_name = f"Q{sec_key}{i}"
            q_items[var_name] = item_text

    # Compare
    for var_name, item_text in q_items.items():
        if var_name not in sps_vars:
            report.missing_sps.append(var_name)
        else:
            spss_label = sps_vars[var_name].label
            # Check if item text is approximately reflected in the SPSS label
            # Allow for truncation (SPSS labels are often shortened)
            item_short = item_text[:40].lower().replace("?", "").strip()
            spss_short  = spss_label[:40].lower().replace("?", "").strip()
            if item_short[:20] == spss_short[:20]:
                report.matches.append(var_name)
            else:
                report.mismatches.append(
                    f"{var_name}: Q='{item_text[:40]}' vs SPS='{spss_label[:40]}'"
                )

    for var_name in sps_vars:
        if var_name not in q_items and not var_name.startswith(("id","RESP","demo")):
            report.missing_q.append(var_name)

    return report


# ══════════════════════════════════════════════════════════════
# Methods section generator
# ══════════════════════════════════════════════════════════════

def generate_methods_paragraph(session, study_dir: str | Path) -> str:
    """
    Generate a structured Methods text block from the study config files.

    Returns a markdown-formatted string that can be inserted directly
    into Chapter 3 under "Instrument for Data Collection".
    """
    study_dir = Path(study_dir)
    q_path    = study_dir / "questionnaire.json"
    d_path    = study_dir / "demographics.json"
    c_path    = study_dir / "config.json"

    parts = []

    # Study config
    if c_path.exists():
        cfg = json.loads(c_path.read_text())
        n   = cfg.get("target_n", "N/A")
        parts.append(f"The study targeted a sample of {n} respondents.")

    # Questionnaire structure
    if q_path.exists():
        q = json.loads(q_path.read_text())
        sections = q.get("sections", {})
        scale    = q.get("scale", {})
        total_items = sum(len(s.get("items", [])) for s in sections.values())
        scale_desc  = " / ".join(f"{k}={v}" for k, v in scale.items())

        parts.append(
            f"\n### Instrument for Data Collection\n\n"
            f"A structured questionnaire was used as the instrument for data collection. "
            f"The questionnaire was divided into {len(sections) + 1} sections:\n\n"
            f"**Section A — Demographic Characteristics:** This section collected "
            f"background information on respondents including age, sex, marital status, "
            f"educational level, occupation, and monthly income.\n"
        )

        sec_labels = "ABCDEFGH"
        for i, (sec_key, sec) in enumerate(sections.items(), start=1):
            label = sec_labels[i] if i < len(sec_labels) else sec_key
            title  = sec.get("title", f"Section {label}")
            n_items = len(sec.get("items", []))
            items  = sec.get("items", [])
            parts.append(
                f"**Section {label} — {title}:** This section contained {n_items} items "
                f"measuring {title.lower()}. "
                f"Sample items include: \"{items[0] if items else ''}\" and "
                f"\"{items[1] if len(items) > 1 else ''}\"."
            )

        parts.append(
            f"\nResponses were measured on a 5-point Likert scale where "
            f"{scale_desc}. "
            f"The questionnaire had a total of {total_items} Likert-scale items."
        )

    # Demographics
    if d_path.exists():
        demo = json.loads(d_path.read_text())
        demo_vars = list(demo.keys())
        parts.append(
            f"\n### Method of Data Analysis\n\n"
            f"Data were analysed using descriptive and inferential statistics. "
            f"Demographic variables ({', '.join(demo_vars[:5])}) were summarised using "
            f"frequency counts and percentages. Mean scores and standard deviations were "
            f"computed for Likert-scale items. Cronbach's alpha was used to assess the "
            f"internal consistency of the instrument. Chi-square (χ²) tests were used to "
            f"test the stated hypotheses at 0.05 level of significance."
        )

    return "\n\n".join(parts)


def write_methods_section(
    session,
    study_dir:  str | Path,
    api_key:    str | None = None,
    model:      str        = "gpt-4o",
) -> str:
    """
    Generate or update the methodology chapter's instrument section
    to be consistent with the actual questionnaire and SPSS file.

    Updates session.chapters[3] if it exists, or returns the text
    to insert.
    """
    methods_text = generate_methods_paragraph(session, study_dir)

    # If Ch3 already exists, inject this into it
    ch3 = session.get_chapter(3)
    if ch3 is None:
        return methods_text

    key = api_key or os.environ.get("OPENAI_API_KEY", "")
    if not key:
        return methods_text

    from research_engine.writer.chapter_writer import revise_chapter
    instruction = (
        "Update the 'Instrument for Data Collection' and 'Method of Data Analysis' "
        "sections to match the following verified questionnaire structure exactly. "
        "Do not change any other sections.\n\n"
        "VERIFIED INSTRUMENT DESCRIPTION:\n" + methods_text
    )
    revise_chapter(session, 3, instruction, api_key=key, model=model)
    return methods_text
